apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:W3ie4AK6HhnyNTJMboRL3GEvWgUOD5E+KCKYDsnCsxt6NDTIG7fWKQ==,iv:EQnPVy7g3mmLdZXLi3tOXTaYfsH+9ZWruM6TdAb2w80=,tag:vHMSdfONC7kN5QQk+PE8ow==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU0V5bnd2K2c3MEhjRmRX
        U2E0UmRlSG9CVlRvNkw5VXV6bk12eGNpTW5zCkM1TnJFNVkwQWtPeUxYT3IzdThz
        dkxnMVRyRThFeTRJbHBPbzZzWUIzY2cKLS0tIFUwQ2NkYWtiMGVJVkVLWS8rRVFh
        T29SUk1EMkVrKzBFMFl3YldiSGgvaTAKnT6FLIsoLMn44OS8vsS2c5dTZX1pzqpY
        6v+hYygCNvCfOCfGAFSKZgmwwdd16rnW9MeYFhruVzS0BIPIkXGrNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T13:28:06Z"
  mac: ENC[AES256_GCM,data:+N0m6fgEV3w/AToYnuweTe96il0YrLH7GGHDeFs+70QLWaw5zmyolnbibkCJcLPCPCJQmjuqt93Eh9p8pXuvuZre4xiWaz3xDmfGTM52Mc5aQxjp2zePHg0WQc8AeGTxwaWQrPDhM2XwHBTN7QfdvRHpvkT47jn7nhkkCbEbZ2s=,iv:PXyLzk5FjuHZ+hyjaVFCfVmaor8vln7QzlIK3UvnWXY=,tag:gxQQBgck+yEnoAgn0Ye25w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
