apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:oavcymNczkoieiSSJPXTld5ldYPUr+Gkl3skqM1ACHBcF7F3vWhHkg==,iv:NTGsEdojz7Cq2/kcUgCwxqUUXbWsInvkWrgfb4bs2Ec=,tag:xK7K2C5Uu5JqJPP8bMQz5g==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreHU3bnFyNEp2M25SLzdD
        ZmhzaFpIdFRLNUtaK0k2YW4ybHd2cklHOWdFCnlHWG1ocmZzQUlCeXhVMXhNN2lH
        VzEzTWFSMWhDNG55THQ1Q2JjQXl6cVkKLS0tIExVOG9WMi9QQ0RCLzNvOU5hQjJF
        RVlkUWdkMHZHNkpHL2dYODlBdWd5UFUKE4NJsgY+4z67ZZ53kD9Nit9CO8F1BqUK
        HAnwf14uEUkTi3s8hJxJuJGnH5Vs7Cz4I/zoD4pJz9eyxqCaoDvRNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T16:32:00Z"
  mac: ENC[AES256_GCM,data:brOWK0mwwWRf/cfCpd8jmouWUZYo93uN5SiFDLnnKiGT93yn1L+j/Tq6O17Xv8EcaQtmsh/FaTJar6mC6Te6WT0oINY/UofE1s7mGKMzMaeC2mqlP++nGpzF+i8IyuT0w5wTmH2oAu3QaPn6Hxaggt4UjqH8jP9+1J6n/RSvnsk=,iv:loI2exrCRGQaXYcfm/cfGvnlEALyv+PlzsoHzcQMR3A=,tag:ZAFtoARnGzgKpJBBL492uA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
