# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: obsidian-couchdb-secret
type: Opaque
stringData:
  COUCHDB_USER: ENC[AES256_GCM,data:lGuprbgWPoAfy13Q,iv:23XL9UXJUaeH76WLaV2OaH2ZFYp8lQPj89tL55B7zlo=,tag:mEziTnzVXLf1mGgp650S7Q==,type:str]
  COUCHDB_PASSWORD: ENC[AES256_GCM,data:IfCCiAVTaYvg4Mz93+RKrxrTqA==,iv:Kn0ZE/8Hatpylu3ry6CZwoy64zOnDCwDn++EYpImXUk=,tag:jZK3NWqAE2LBQMY+Qu7Vfw==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNElzTG4zUXkrRXBNT2tD
        eTlrb1haYXVvb1VYMkRmMEk2eHJBVDFCOTJFCkpOZGY1ckU2RndjT2Qxc29WYlYz
        WU1JenlVN1FvTE5xZnVxRXExZTJ0Y2MKLS0tIGxEQm9qVHQ0RWlhaEQzT0dESlBj
        OHpkS3NrcWViOGdJVnY0MUJJUUgrSU0KSV+lWHz2YMWNxqE5IF9IMDXSt2MqyHPs
        xQlf3fSQYqBsZMRK9ihKWis4ZF+EC+zc9RfkqaEBtX1CjzfguKWumw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T11:16:22Z"
  mac: ENC[AES256_GCM,data:jkABdKQym4u4eQPfaJbhAU1yFdzClxa/VjdMQNfdTXphhDF8t7NKtD7gSD6kLiemNZn+Nlon9HJObEDcVlzLXEJEGxTFaAr9WqAJoFPefTHrl9Gk7CMKzCvzLxNkrR5X0x9whnbgZoSXLc51qqcXcemAJv4d/g/ao1p6e6IMTOg=,iv:JDvA6wpF931sW4WfUOHkE9TXZh3/vAZQRVsH2Z4P7aM=,tag:r7CQhtM0Lm9iX/UztKrKNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
