# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync-secret"
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:AO07w1OuzUTXzdjrSObsostQRDiTgg==,iv:M3qKDcgLdkoQyFuLpqgIBrICftC7NZSOZ7QwKvFbWtU=,tag:ohdClW9KG8pQ7NJC9cYQ4g==,type:str]
  KOPIA_FS_PATH: ENC[AES256_GCM,data:l+18olYdH1xcrqY=,iv:0Skw29sOn8BFwLdmB0ydQS631lcck5IggwAh9VxPpNQ=,tag:CTuohE4F7u8iT6eLqeERdA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:VvCR1cm8phu6hG0ISzQ9lcwmxjE8oaxV,iv:7wIuZXxyoElWP5nKKow1zvvBUbjzK5Rt01bpezRjJUs=,tag:P+2EZBGGI7NSYsAWs7dMqg==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNDFMNExFSzh4cjlQb0Z3
        aUwyQ0xvRWNOZEw1MDJ1ZjZsY3RCVTZPT0VVCkJaRXFZdnlFZXRBZldtekk0RUht
        OC9weHRXWTU4d2hoSGtOLy9ETElLM1kKLS0tIDk1RkNGdjA3UTIyellkbXoyNEFK
        MVVBMVd5Y0lSYUV2T1d1K3NCZEVWVTAKkYw/o7LB+EhMoVcoHIU3dQMM/TSzjL0O
        SDRME9dCktkLDEdDyy3Aso7EbiTiA/f1XGblg0fUbeluVDVO8iYBJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T17:43:20Z"
  mac: ENC[AES256_GCM,data:hkhwdbcHcAdE9QMKW3BEFBWeq+5Pe5b11z7RE5wqTpnYbRKN5pBrLXA1upc8TymLBQ/M7vQhyq1455ACB2JxjEzGsyGv17IOUO2+XNWa8zNnluWBNlr2aUH9fruJuII0kFh/X8Pw6I+uQAhtkDsxOi2DIXoI2hYkM0hsB5ivXRk=,iv:9alrftmqbqM8+7xQ/5NFutpx81I/8eS8k/qsEurscfQ=,tag:DeVY1KVQULG3z0NPiS/Jfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
