apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:96TEzRdRBoIEVg2ClTcN,iv:1IV0fkaWuT37vaQp0u7+zX4NgdBjxgfD6YYeLOuvLEs=,tag:U3KkzLB1K4rIpRma9iFrEg==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NGpxRnF0L2ZWakd3eE5T
        YUxiakRha1NqT0xodUVtb1VwUnRoVHNJTWdBCkxLMGVJTFBmalpZQTVtWDVVT05R
        eFdNWTAxTnJBdXEwY3JjYjlzTVRXTjgKLS0tIGxlejQ0MVZFbUN6ditycmRTTDZ3
        Q3hMclczcWhQVEVjOXFNbnpWeW5RTEUKX4GJKCyugasrWXBoB2hxW8y8f3e266qS
        oawoEA5NKoF2hw+d9Lyhd/m1nUsmad+zk4cPjVHvCttJ28XFpN8onQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T18:41:50Z"
  mac: ENC[AES256_GCM,data:GFR16kVSP55YIybeDXlsLFn/+LEIkNti3yNsyLw6UhCZpADv2sx3KPFWHcqhwKOH8b8arwU8jEBd7DNcyaNl3LoVae3JOsJzwSDiQ80d6BcJyDwm1JlVMteqDgQMCmTwzMse+ZdweNBNAtqsK534vz6JJGRCpHd6fOZU+N3ev1Y=,iv:Jm8OtSQDb7F+R46q8LfZJeVMAOxuqbDG/9zASCMmEz0=,tag:ykGrSVT5+HxHVLYvEdoyzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
