apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jYi/DW8LsIKFiaThmrqq,iv:eZGFuQMu+9eTU8Q+3Lt8DXOcQa56UipVYE6vqAZ351M=,tag:n8HWhzr43nP95JnYXgEMXw==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMlBJYTd0TW85K1RQOVli
        N2l5OEZraFhiT0dpN0R0a0liUFlHQ29LajE4CnA5K0dXY0V2STU4YVJBNFBBYS9H
        c0I4V2V5S2lsRGhlOEorTUVqMzZZVTAKLS0tIFhJQzhId1BxSkRxQU1zRExpMExk
        TFFNZnl1a2s1V0ttSXg1N2hGYXhNQkUKSZOwolKepjt8JlxVoFjfUmk0SnVilT4e
        XqVEEbjk86+33T/aCcemjV8O8Fdo0gGlYkQG/FZjscK5ltBmqy9wfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T13:28:06Z"
  mac: ENC[AES256_GCM,data:cbek1epTo69az2jI7HGKRJP9JFOdVEq2NYxlQX9s1te6TB3LhahVN8tYsIAQXIew5w6KGvJzfuqNpyPBM051PegYQMq4u+hRE5cKkgR7VhqNz0qtsYV2Es711qZj5NOr0yuQrGERxjhTMzB471Cm0+a+U7WxfK+R+k1x/Ekqkvk=,iv:dqdYmlG6QGAhOxqwtrNa6zvFdu8ostyv0aYdTa3N/xw=,tag:QhQhNk7JV7OZbhtXydXOpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
