apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:C9MFtP8ZL3Wj0DyN8yQH,iv:BKXgIbNlv2nlDoDkCysXZAO9maFwG9LVeDakZJHFu88=,tag:f3kx+2MlMfVTgs2uH5OZ8A==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSzhaRUQ2ZWNEaWRFVEV0
        WVJhYVhYakVBdmtZZlhRNmFRUlVCcnNjYUQwCjdPUzE5ZDZzeUEyV25TR2g0Vklo
        SERJSDZuWnVYQzZTaHRHR2NzMnhmWFkKLS0tIFg1TzU2RkJXemRjZTM1WXlDRVlW
        TFVRUFFReFBwdEx0a3g5V21DeWRrMmsKcD4VaXJP1JPPQevuFbYZYS2kcT1YnPIq
        7DplRJgHtUo8qN1t/qRFfgKMrTFWlmpUsK2Yzf11FgLu+refX+TvsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T16:32:00Z"
  mac: ENC[AES256_GCM,data:FjTr6CwdSoZIX7XX6ELZzuvhyC0lgbUmRmT15LF0L+uY19z/2Yta2eCNn7y48Awk75nP2MoSFC1IAKkzylhydPnBhbJ3uqL7PyWc4tyq1qP9lPBjOQ+9X8YCCnqX1HpXAS7fgxybt1+MAM+0oxny8cM5jP0mc3ku6BHdr6scruo=,iv:sB/M+uzEMC3igR3QRA6/aIXF7o2JavGY+ezykpA9oXc=,tag:lUEQYj3HQJw0b48xW/mbFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
