apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Y1+XCa5D2PiUDsJRfXK8CzW0/FTCNwOWgupcT/c9dhg=,iv:K/FRHBGS8CJyiOKz0mZcOrcxJWzPP3JUEQ8zphEjGTA=,tag:scvBBRtocBuBIeVQ+uE/7Q==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3T3BWWEJqK3diNTgzU1lQ
        VU9BZWhwVy83amFMOGszWjlIMk4wSlNKcWhNCjhWRjl5MFg0NFNETzZhUFFaUzVu
        eVgzaHdwb21QR3cvbWNHd2pXQnU2YzAKLS0tIE5lL1lnN0xadDlkcENNRG1LMnVt
        R21PcUR1QnhZNG15MXBZWjByM2pJTFkKZ1gmsqv4XCCM1kYlQYVgzNfXGhpXbv6r
        zSjEXmu3v59pzpotUsnooPLC7Ox+qPKdgSak5P99ECgqY1I4r4CPoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T13:28:06Z"
  mac: ENC[AES256_GCM,data:q+ZQpk0s91N4XmkMg+If7xh49ncFbkjceXccmGM4paAg9bt8GRn7WSHN16dxZLLvX5x7qvP5hm5vnrZK5JgJ07Mp3m1XYZLaeRu6ccTf/UCqX0fAZgBvYoC9ITrLFx74mnwTDCQMH2tk0BHxegUtFCDb9vYRzp4Yyx3//a16jKY=,iv:FGGrX4cI8dvuuC994lKiUcnbqpYx5caMar6uKoDod/I=,tag:N/c8r8qGIFLbsKujW+S/jg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
