apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:r3Cdbqwp79ojnlBoZt9oenjuFhYGD0pSwNaOPYzjSDo=,iv:A0ukuqD92WUFt1laa08tz8LLlg7ooAtP/lVLuRqgGaI=,tag:2Bw4dbQ/6uZGSEzemCUvRQ==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a2N4TG9KOE8rdXR4QlFq
        Qy9SSVp3MWhVcGhNeVdMc3BUTEd2bkJhM0NJCjgvM0lXUzZHaE5PdmlYMHF4dUJP
        eHRUU29xc3JzZU9KNDNHUjFjTkMvM00KLS0tIGxBSVBVdFBPZjFwMm1MY0tSdlRP
        ZUs3Y2l1aVd6Q1VOSU5zbWhqTnQyMUEK3wPgVqoyV+kqcYEBeQwUoayhZQenheZl
        JUJaHC7wuvX2W7ctlZ7EXwWh2nW5ts6abJfIq3Uf+Sz3kmu0lfnUWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T16:32:00Z"
  mac: ENC[AES256_GCM,data:nL+dcq3YQIVoUJZ0EyrUaOhPW5G6eKEwBAecjGNeD/IHAvTLd4FcPbcIiu7pinvMJVa2o+O/XmeKg38AlMdEuDrtYK3uYVBBu3HKFj006b8OBkcCwKOIWKE7QLOCS+8NM1GpffSPPitzp7qqEWvdjr3VL296nn9RiEVxvV2m9fo=,iv:O6LAX0YrUDkX99W/ODALFd/fDhZzZckvbbpqxQ0H2kc=,tag:0u6shIT6cj0FD6qe70FqYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
