# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:1Mmov0VtsiE6d3xjuCmicDDBZaJvHg==,iv:3zMqDu4kOi1JAEvZDivrPhq4WDfB19GEfX147DtGbvY=,tag:3ju5CaE8vhzeHHQnmmRIcw==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxc1AzTW1tQ2VYS2gvNmlk
        SFpGcnE0K2EwODdmVHZiR3diQ2FiRjUxMmo4CndCa1EwaDVBdHhQSFNleVA0ZFRh
        dG84NFNEb3FFSmU4bVMrcHMyaW1CZHMKLS0tIE1aOFZ4dlVIWDJiQlVjNm03Q0k2
        THJzeEtzOW1VZi9UV2g3ZExUVkJvVjgK6iAjebJMBQVgyCZ3OpZ14h1PcsaaVVI+
        g5ZDfH1JaT00yWDT1R0IJpfgHECjgnRLogwoEqpgB7mLQCcqQKXc5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T16:10:53Z"
  mac: ENC[AES256_GCM,data:s3DOvygCbOs79qU5MA3GpyUA93BG0jz3GccXS4CCNvod7Ynm3UWNSeCU7MrANuRsuNJU0axqA2fQ8iICs3WlanSKwbbqihd47oHTW4Y0S3Ey8mrxSRvt6XfodEoVjGpRVU+1G8xXncR2tYIu1P6V7SotPJrlQsL/JdAo/6mqAsQ=,iv:4GPApi5cQeSVW9ynQScK1LTIb4cKMayXWvey41IIq8s=,tag:/zaTrubtlt39xgnngSF2Bw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
