# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:OLXAhII+gireP8tktbWCTAh/Asnprw==,iv:H2PfPqwQ2bWr5AgyY/APfoskCzoCGkCRq7XPb1UVOTE=,tag:r6zCstQnYktkjV0CMZ7C1w==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb3BuTSt1TXJIOS9QZVB3
        QlVMM0xJdk9Nc081U3UyQktHZTlqT1BLem1RCkNHUU9nNVNBQUJjenk3WVdQRlpN
        aS8rRm1zQzZ6bmVlR1NRQXZ4b1h3NXcKLS0tIGxZN0pkU2JpTTRZU2lBYUo3VlQy
        eXh3RzBiKzJvU1RPQXl1UkFOdTUxMTQK0cm2YcJJWsLM0FJk4Bi7edyC/Z6EhPQy
        D7FORSpvRgv482qZktWI070zIkyIICod/RXnUXFwhHoge0oVf5LMIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T13:23:27Z"
  mac: ENC[AES256_GCM,data:BuU9On5i+VU3mDPIYalTAPiCfUyylxSPXb3uLeQJEU+TlXsnjin4fWC9XnhHBO83MyD9+Kd149tib8lq43oc8aDrKed5Ka06uMMiCHcLEMtOOU46LO7enQJmoxXzLmS206HKIj4Qzi6tQ1CVyTPNmUqPvkWT9bkDTBUxJpHodXg=,iv:3agPQZdXMglT/BlSqQF6T9sUWDMXtfmPFj98grAV/ZY=,tag:fiklERcujulAikNIk1NDvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
