apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:il5hWn5KQftDQGPSUx41XTV5awRbifPsAjH/bmFVT2ia8T0rzHhfch1gF33DSXTJeB5nYjMsr9qUWSH5+Tx4fa3o8P0r71Jnz3/cmvvkfw1rITkc7w190n7p1roSssFTTYmFfVn9da9Paa1VmoRhiE8/gQYiwBLRgF5F2rDa32xtC/jZ/azOMdOvldKwl7jz13+M+fjumk1xEQbYopvAFanQ2Uwis7Yy6r0Rnwlx6l7BA1q4,iv:MaI7I2jt19/DC5Ua693mfTiGArC90zjNr8VOJXJmL9Q=,tag:wxNy8spUVT5RDjNM/HeuZA==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOWdjUVBabzFhMVBEcUZ6
        dVlMOXhpNkt4OUF1TG1UQ3NOcUxKRk9TUUZZCmNCcEw4aHlOeE05S0lTVzRlRnFF
        T3lmRFRGRWMzYzRlZEpQVEFWWGVyenMKLS0tIGd4anVqcjhob0JNbmc0REdtNUxB
        OXBqY09vdzIybjFLYzk3ek1wcy85dmcK5u1OwuDA8R7Vx565z9EgOaOWGEdl3DBf
        KuX1SVJMVNtJXeliaMexWWaoTQXcg49NaWDnebYPUO2+zBmYlnwynQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T18:41:50Z"
  mac: ENC[AES256_GCM,data:D+nkXnv5aEkGChchsCse3+U8x3Kq7G96xsMi3+heTtBzJtx3WNIUjb+NHxdlwKv4IY3LFWfDyZ78bY0mzybMCcmp28VVpAVrWgy6zklesJ+aumvoDB4qqc87d4fQzfKPkaOAzL3Nviu6eR/631IHBSAzuWWO+86qxor1l1jMXew=,iv:/0Haqg1gqhKarcMYzIsX76pv5eMHTBkHKINNomesdU4=,tag:pIYvKpWk+/lqjHNlev3xtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
