apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:IOveoM10docN+fDQQOT4O7OfcJWHHVX9t86fAP8o9VtctlXyqXicz7wxFQv2jsqaxWS9EtU3W45rJ1z7qNqeZmdKgd64aGqZQFjns8k/hlkGpgdvsAbOsddGCBVrElRYbUhBwpDGrQ2oFMufjEKzJOsms/lQeEiz4ASNBYWkOOu8L6jbYEXUdGLuOIo5RMG07N/lhOJPLZA+2mGh9xlAGLLZgxhxpxH3QVrRqePuUCEDEi0X,iv:XN5e3zoB1L0VhHENHA7Dl1i9oe78gFXDWb/N8vZZS4A=,tag:MmpDaquCan2gQdV6zv3XKw==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNi8vcTNScS80QWUwWW9x
        bmIwa0RZWCtUSW5LSUFIbHppUUNUMFFPbWlZCjZ4S24wOTdyZGdnQWdYZFRVOHBn
        M1RXUWIvSWkvT2dqYWZPZFdsWTR4d2MKLS0tIEpFWHhrVG05dEw0OGg3VzFVSWdP
        OUlFSnJnbGg5L2F5Y09mc1JPdUQrOE0KzqSB3TwoYtR+oGpx6H829Q3X8FSpdS+X
        L4q69685bNvwgBOoyCpWUlXtEeyd3OdFr3KkquAh5Nte9EqOLsTxoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T16:32:00Z"
  mac: ENC[AES256_GCM,data:TLRurqUtKwDz9+zvnMxxFTuSnhx4xnpvXIQympgLpRqLLR7fx5/cmhlYRTd+ExZhwCT/Vf1fEA4vKI4rD63wm3o2ev86JBc5+4X99VbxAi4e9ofHsBt5kJud5sEinXNSSu00cztHw74LguHsRkaPmISIxB1yNGlrt7ldm6AxQSg=,iv:DbM/eNEd6n1eTi5kE+XtSDRUayFJJ+kOe+jp33m7LFE=,tag:3AGpDCJOpbgo/msRVLJXEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
