apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:xKfyDUc49aq4D0iDsooWGXNWaOO0RqcSg9dJdHMW4YteT3QpwG2nZQ==,iv:I2lrimS+j/qhnHIe6PquXZMoUIcWAMmuTtXjJZ044Ro=,tag:pux/X9NOqLu0SakdH7z4qw==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Ymo4S1JDVkMxeVRtbEhv
        UkJDRGxrUVVMekVrK1lVRVF1a1FKb1Z4Z0RnCllSRnlsT0ZGRVlRdDRqQWRBUTJH
        SEdHYWhMaGlVRk5rbWNCcXhIak9GN0UKLS0tIG1SVjNTUDcvYWN4ekFSUnBMNVUr
        KzFCbmV5dFlJQndpR3RMYXl6OFlWaVkKgm1EqcjgIM2A6y7eiG424Qylydiluzl5
        gavjeceTGeoHM+MPFB3n4/HdbkZS93BLZno9nwOK9eOIMhhLR9MeWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T18:41:50Z"
  mac: ENC[AES256_GCM,data:gbnWNwCE6Bbse2rXhNe9/p94Nx9Nlp7ivQsewX+UkEqU9uRu5VsQ+TCGL0drZwQWtH9MF2g3qqtyLudxF0q0cip9qaKB8e7sHIlzqIzaoLu0n2BKwhu8QLd/Flqq599tCfGpXGBJqMVsdU47kDR7A7mIRhYiwpfUUGZcYXIwLI8=,iv:OimiOMJLyNqGDpxVLNT64wPiNSepvCL+PIZ88c3XPgY=,tag:WepWFCpZF8lA860/LDcZ9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
