apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7FctadLWllbBVM9WPgkLyeZHqpknQM9VJnxP+h7RqNonnW+QOFTj1A==,iv:VHrlhvbooMWShptB++HO7BMA5xxlJii82OV0N2l4MUo=,tag:6lHPLwa4x5DThWlWNyau3g==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaTUxSmY1VVlIUkYzTndV
        NlM0clJKUmtkSWR4SjVTK216V1gwaW9GaFZjCnRXamRMUVYxQjlZWDJrMlhPcHVZ
        Skh5TG52SDBnN0t5RmZ0aHI4aXFVMVkKLS0tIEI1MzZ4aHIycmpudE5CUGpQYlRI
        RHZ0YldzZVVZMEN3dHd2a00xeWhZM3MKQWuRfaCUcnOup0BJW3VHdNHf4MgXzZCV
        v6T9vDYif4bWJ4pRDKRV/04hivQ5wmBr2cWHzzIJ8VxnRHsFJmHRdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T13:28:06Z"
  mac: ENC[AES256_GCM,data:vzXZJNsJdeDnxhDWnaNjf1Wsk8Y56pYkzxtuN18Q6e3jr9YSGuou3RdhvZ2VntSYK7iq/HxFHU64QAl0s/KtBQezqUjY8kedNpR6pm+fosNDde2jFQq+Ser7jKfJ6RvF1diPY5EQLuUwbADQlEhUIT/60dwLhhmjti1w3aCl3/Y=,iv:dUVVYoI4jtYGn6JNw1dtBiHId2JvX+QGuBD9ow/gJC8=,tag:WRdzZUqLyx/+fFNSzueU+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
