apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:unm3XEZyqvVrDBMfHNlxzOuMG6Ze85tHADqo/v00ndXwEVJRxwzXQg==,iv:nPbRLRqnIpKm01h5l4N3NlIz+I6aNbhdB9Pt1z8ccCo=,tag:xCbWdMXcIIc9fcQSAVPiGQ==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYVBhMlQ2UjVoa0YrcTQ3
        K0NxY3g4a2s2MEUyZ2tyaCtjZGFJTGNxWlE0CmdpVHVXYjF2bHBRNWdxRnJGZmU4
        dWpudG9BaVRycGNOQXBUREt1WnZpbzQKLS0tIGIyN1lzR1hCSEhnUy8rZWV1N3pO
        dWIwT2x4Z2RiL2NMVUhVQlo3ZElYalEK0RFIoaTx2kK17oR/S7AJXDLn0vijgyoe
        sLp5WjnmphCXsqKlVYN/+HsbZ/ynx29kA39MK6Kr2NMAzPejXC0yAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T16:32:00Z"
  mac: ENC[AES256_GCM,data:EaeeuBRF3OlxZmn9YSuve8aZDndkncU1HouOTffjhjqewkQVXzHx1FQ4m2yHfdYItSzjOBd/NQFhh6DcxZ+55NjvDNThdW/CAQEY4I+AYuV3OqneY5ay6VUhN2ryc2LTSrF68iJHCCJ5PDdQ/VPe0f2ttT0dJmlLQ0tipddEajM=,iv:6epgBF2Z6ZHqMQlK06peft+SZ6zWluVxsLL0TnABYuQ=,tag:jl7YY+qJrs71vuqAjUrokw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
