# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: pihole-external-dns-secret
type: Opaque
stringData:
  EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:uvhu3DB2Oib7,iv:GzqfN+qm3nn35Jkt9/MQyFg2awr0URidQdvDG4EcJe8=,tag:QhZgnpAKo+aqQzj0q8wG2w==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbjV3WTBMa01FNWhVN2lU
        aUZMTU5Ucm5uRGpIalBKdWpEWTZibFEyNkRRCkdBYlF4RTMvSUlFdFliNVVsRHRT
        a1FobnArbVFrb2dBM1ZQbnppcG1CTUUKLS0tIGprNWJmTGgyaWEyeWZGb2dtMnlE
        YzVORmc1MFd3dDkxTTFYUVdKbjVyNnMKfTJy8CEIS+JHzUarbG0d2NkeWgV/Hfmq
        G+J+Luvb5gelVdBf0NBYs4zVK7WoiQdFWCzjvDBSqyacDunQi0vDkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-12T18:23:14Z"
  mac: ENC[AES256_GCM,data:ENJsG53HC69a7to2lxllsd8HL1Fb3TTTOLQkTTo3qPOPU1TyCvOqYyfEy5DFLlFNt1MaUsgHNgvb87hXPOxPzLJeVw7S4hw+fROkoiHDGx3GsnHKJkXb8rJLv5IExkAcxDi+JXIJe2U18FC7ztYSoKY0SPXKORO2JSADWQhxSkY=,iv:i9+62LAdCAOHh7My+vzxKEY3V2Crqfr2DOLJ/i6aubU=,tag:sHOaU21UGDisyUWUDL1N9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
