# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:eUDPVryWCTcO3f8VyeCMdsuW4PNexQ==,iv:5YrLfUEI/fvnlg38C09kn/9XMpcZ9ItD7bF/pGTpg3c=,tag:b9fJ/4e3jJnajrlG4smaSw==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWitFTUphanJKdFIxdis0
        dXozUmxSbWIwV0E0VnkwcEpWUmVlTVh6R0ZNCmpzTEFiTXlQeXh0QnN5OHRrOGZ0
        NHczK0NWZnd1Q28zeGpsdHhEd2xtK0kKLS0tIE9DMzlNMFYvT29LRDZ2dVZzU2xG
        SmZsOXlKK3pTM0N0Yi93V1gvU3N6b3cKfTms0tfkMuB1plTiOfIzSkuWYfUnJSaW
        V9c0NyTgcPr3JrP+FgdynD3c8ZdpCVFqYWj5DYWJQDgYsuQ3ZrjAQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T17:47:09Z"
  mac: ENC[AES256_GCM,data:e0yiutLYhJukC958ZCPiMLW7YnEdG1HQrBWhRZ9Eumyz4sy0v/z3vGn3hkisxINlrhNm6O7sdwEUhsHRhqtBPIhuNFtVIGR53tuaceq4MiNROke8GfAqk2u11eYiBuT3YVqwSZ1B6tLpALk/96jTmTVKKInBEeL/cKP74g/QCZA=,iv:Q+p0r+BpQfUnpnuktP1LBAq1/mydAwDRLUT6VMtou8Q=,tag:WrJMSXKPG0mF047114tTJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
