# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:nz5kT1isy9le++CPGtZCcrt1s3HTlA==,iv:nanBOxPkqbmPC5fXYavhlA7ZfUigMXI6AVcqleAhIeQ=,tag:TEK+h2R0pkcUaOzQ/weczg==,type:str]
sops:
  age:
    - recipient: age1r3u9tnmrl3n4qe507yz96dydf04aw07857cy3j2gyep5p8qugcnq22cdef
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T2xtMjBRV3RkT0d2V05N
        UGNXQmZCT1F5cE55azZQenVjV3VmQ1lUd0djCi9CYUZyWVlTUmFsMWNmNWhKdDU3
        eTRiOXB5Z3ZCVzN3U3hNby9RdXBiL00KLS0tIFU3eDVYN1p5ODlaN05DM2l3ckhC
        MjdDdDJBOTh6RmF3dDdjaTQ4aVRSVlEK5W5xamx9CRTUZZesfh326x3MN5J3o+8V
        4MSO8mut1hPRelbtymBzAeA1hwOFUG0YBKy1XIgFR6RqXAuvyyHgFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T15:30:13Z"
  mac: ENC[AES256_GCM,data:GqLveETqQQCC2NZvztGXdMVQSinxyheyeHuWWPipWwni31Pqyh18wqWfwTrVal7rUHr0vseHhhMCk+mBkzYtZdV3EHTGn2kLvvGgQT5yG3tTMKekhlUxUx2CN37b//DSdMKwK0gX0DGjS3uuAfMtkG7QAli70cB1l01vZEkL09A=,iv:1opQ53Gv+giv727YVgbsqYH8HLG9Nh8QkURe7EpGVRE=,tag:gkJ9rq6aLBamjH6YG7EmJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
